
trigger:
- master

resources:
- repo: self

variables:

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:    
- stage: Deploy
  displayName: Deploy Stage
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'DivineOpsterraformlabs.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: 9240b5c1-a1b2-4799-9325-e071c63236fb
            inputs:
              rootDirectory: '/aks_advnet_rbac'
              targetFiles: '**/variables.tf'
              encoding: 'auto'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              tokenPrefix: '#{'
              tokenSuffix: '}#'

          - task: AzureCLI@1
            inputs:
              azureSubscription: 'Sasrose Internal Consumption Sub(45f7e5d7-593c-47c4-989c-d4745c4a175c)'
              scriptLocation: 'inlineScript'
              inlineScript: |
                cd aks_advnet_rbac
                terraform init
                terraform plan
        