apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: devops@bright-skies.de
    privateKeySecretRef:
      name: letsencrypt-account-key
    http01: {}
