# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  connectionType: 'Azure Resource Manager'
  azureSubscriptionEndpoint: 'Sasrose Internal Consumption Sub'
  azureResourceGroup: 'airlift-aks-rg'
  kubernetesCluster: 'airlift-aks'
  dockerRegistryServiceConnection: 'eaa59aca-42ba-4064-8d77-e7668962622c'
  imageRepository: 'divineopsterraformlabs'
  containerRegistry: 'airliftaksacr.azurecr.io'
  dockerfilePath: './golang/mywebapi/Dockerfile'
  chartPath: './golang/mywebapi/charts/mywebapi'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'airliftaksacrf709-auth'
  namespace: 'golang-app'
  hostname: 'mywebapi'
  dockerAuthSecretName: 'aks1aksdockerauth'
  releaseName: 'mywebapi'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          
    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'DivineOpsterraformlabs-1598.default'
    strategy:
      runOnce:
        deploy:
          steps:

          - task: HelmInstaller@0
            displayName: 'Install Helm 2.11.0'
            inputs:
              helmVersion: 2.11.0
              kubectlVersion: 1.10.3
              checkLatestKubectl: false

          - task: HelmDeploy@0
            displayName: 'helm init'
            inputs:
              connectionType: '$(connectionType)'
              azureSubscription: '$(azureSubscriptionEndpoint)'
              azureResourceGroup: '$(azureResourceGroup)'
              kubernetesCluster: '$(kubernetesCluster)'
              command: init

          - task: HelmDeploy@0
            displayName: 'helm upgrade'
            inputs:
              connectionType: '$(connectionType)'
              azureSubscription: '$(azureSubscriptionEndpoint)'
              azureResourceGroup: '$(azureResourceGroup)'
              kubernetesCluster: '$(kubernetesCluster)'
              namespace: '$(namespace)'
              command: upgrade
              chartType: FilePath
              chartPath: '$(chartPath)'
              releaseName: '$(releaseName)'
              waitForExecution: false
              arguments: '--set fullnameOverride=mywebapi --set image.repository=$(containerRegistry)/$(mywebapi) --set image.tag=$(Build.BuildId) --set service.port=80 --set ingress.enabled=true --set ingress.hostname=$(hostname).0ee3958d842446808949.southcentralus.aksapp.io --set imagePullSecrets={$(dockerAuthSecretName)} --timeout 900'
  